version: '3.7'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 blog:create_app()
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=blog
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=postgresql://flask:flask123@db/flask
      - SECRET_KEY="dev"
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask123
      - POSTGRES_DB=flask
volumes:
  postgres_data: